# Generated by Django 3.2 on 2023-08-31 13:46

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Введите слаг категории', unique=True, validators=[reviews.validators.validate_slug], verbose_name='Слаг категории'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Введите слаг жанра', unique=True, validators=[reviews.validators.validate_slug], verbose_name='Слаг жанра'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Введите год выпуска произведения', validators=[reviews.validators.valildate_year], verbose_name='Год выпуска'),
        ),
    ]
